### ISSUE TITLE
Web Interface Port 80 and Teedycloud Sidebar not working

### ISSUE THREAD

**Issue by schmersgahoven** [mrueg/addon-teddycloud#2]
# Problem/Motivation

First of all many thanks for your work and effort to make this happens.
I got the problem that I can not enter the web interface via port 80. Via port 8443 I can access the web interface of the teddy cloud.

![image](https://github.com/user-attachments/assets/97841136-5f3a-4127-a0bf-e3d170afb139)

Second problem is that if I use Teddy Cloud Button on sidebar of HA the page is blank an nothing happens.

## Expected behavior

- enter Teddycloud via Port 80
- see Teedycloud front end via Teedycloud Button on sidebar

## Actual behavior

- nothing

Hope you can help me with these topics.

**Comment by mrueg** [comment]
Thanks for the report!
Is there anything else listening on port 80 in your home-assistant or do you run a proxy that uses this port already?

**Comment by schmersgahoven** [comment]
Not that I know of. And I don't have a proxy either. If you have any idea how I can check this, I'll have a look.

**Comment by mrueg** [comment]
Tell me a bit more about your home assistant install. What method did you use to install it? Where is it running? How do you access it?

**Comment by schmersgahoven** [comment]
Setup is: Fujitsu Esprimo Installation via Home Assistant Installation Methode generic x86-64
Access via Cloudflare Add on.

**Comment by mrueg** [comment]
If it's not loading, could you check the logs of the teddycloud addon for errors (in particular what it says about port 80)?

Changing the ports in the home assistant UI will like have no effect till now. I've made some initial changes that will have an effect on nginx, but need teddycloud to support specifying ports in the command line as well (I'd rather not mess with your config). See: https://github.com/toniebox-reverse-engineering/teddycloud/issues/217

**Comment by schmersgahoven** [comment]
Today, acces via Port 80 is working for my setup after uodating top supervisor 2024.9.1. But Sidebar is still Not working. Got the following Message

![Screenshot_2024-09-19-21-26-59-727_io homeassistant companion android-edit](https://github.com/user-attachments/assets/ff73207c-5c93-409d-94ee-0d4473ecedec)

**Comment by mrueg** [comment]
Good that it's working via port 80. I'd recommend to reinstall this addon with the latest changes and see if that changes anything for you. The screenshot is very unspecific and I would suggest to check the logs.

**Comment by mrueg** [comment]
I've made a bunch of changes that should simplify the setup drastically. Please test again from this repo here: https://github.com/mrueg/hassos-addons-edge

**Comment by mrueg** [comment]
Closing this due to lack of feedback. Feel free to reopen if you still see issues.
