### ISSUE TITLE
HASS on RPi 5 installation not working

### ISSUE THREAD

**Issue by empx92** [mrueg/addon-teddycloud#3]
## Expected behavior

> Install the Addon in Home Assistant ;)

## Actual behavior

> When clicking on "install" following Errormsg pops up:
Can't install ghcr.io/mrueg/teddycloud/aarch64:dev: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=dev&fromImage=ghcr.io%2Fmrueg%2Fteddycloud%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

## Steps to reproduce

> Newest Home Assistant version on Raspberry Pi 5
> Add Rpository to addons + try to install

**Comment by mrueg** [comment]
Which repository did you install? The stable or edge one?

**Comment by empx92** [comment]
> Which repository did you install? The stable or edge one?

I tried to use the stable one

**Comment by mrueg** [comment]
Can you show me how the repository looks configured?

This sounds like you added https://github.com/mrueg/addon-teddycloud instead of https://github.com/mrueg/hassos-addons

**Comment by empx92** [comment]
i tried both, and it is always the same error message

**Comment by mrueg** [comment]
I can't reproduce it locally (raspberry pi 4). Could you provide more information around the system you're using?

Please start from scratch with teddycloud uninstalled and the repositories removed from the addon store (make sure you don't see them in the overview or ideally restart HA)
You can also try adding https://github.com/mrueg/hassos-addons-edge as another option if that still fails.

**Comment by empx92** [comment]
i couldn't reproduce it today, because suddenly it worked with https://github.com/mrueg/hassos-addons and i don't know why.
i didn't do anything other like the days before...

**Comment by mrueg** [comment]
Great to hear it's working for you! :)
