### ISSUE TITLE
Port 443 already in use

### ISSUE THREAD

**Issue by tschoehansen** [mrueg/addon-teddycloud#4]
# Problem/Motivation

I am using Home Assistant OS on a Raspberry Pi 4. I have installed the NGINX add-on, and after downloading your Edge Addon, I encounter an issue when starting it: Port 443 is already in use (by NGINX).

## Expected behavior

The add-on should start without issues.

## Actual behavior

The start process is aborted because Port 443 is not available.

## Steps to reproduce

- Install Home Assistant OS on Raspberry Pi 4.
- Install the NGINX add-on.
- Download and attempt to install the Teddycloud add-on.

## Proposed changes

Is it possible to assign a separate IP address to the add-on? For example, Home Assistant could use 192.168.1.10, and Teddycloud could use 192.168.1.11?

**Comment by dariusaurius** [comment]
According to this post, it is possible to integrate macvlan to an HA and an addon:

https://github.com/home-assistant/architecture/discussions/1034#discussioncomment-9836578

Regards

**Comment by tschoehansen** [comment]
Alright, I need to test that out. Yesterday, I installed Portainer as a trial and set up Teddycloud and Macvlan there. But something went wrong, and then nothing worked at all. Thankfully, it was only on my test system.

**Comment by mrueg** [comment]
I think this is a bit more difficult to solve, happy to review an PRs that allow this :)

**Comment by tschoehansen** [comment]
I have now solved this problem as follows: 1. NGINX runs on port 440 2. Fritzbox redirects external port 443 to Raspberry Pi port 440 3. Teddycloud can use port 443 Flaw: I can log into Homeassistant externally as normal, internally only via port 440 or no https.
